debug: true
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false     #页面不加载缓存，修改即时生效


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR    #去掉启动时大量 CONDITIONS EVALUATION REPORT
