debug: true
spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: tiger
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password: tiger
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-wait: 100
        max-active: 10


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
